# Generated by Django 3.2.13 on 2022-06-24 20:28

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="images",
        ),
        migrations.AddField(
            model_name="image",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="joined_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="last_visit",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 6, 24, 20, 28, 59, 485570, tzinfo=utc),
            ),
            preserve_default=False,
        ),
    ]
