# Generated by Django 3.2.13 on 2022-06-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_auto_20220625_0128"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_online",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_visit",
        ),
    ]
