# Generated by Django 3.2.13 on 2022-06-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220625_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='joined_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
