# Generated by Django 3.2.13 on 2022-06-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="joined_at",
        ),
    ]
